name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml

permissions:
  contents: read

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
      
    steps:
      - uses: actions/checkout@v4
      
      - name: Semgrep with Community Rules
        run: semgrep scan --oss-only --quiet --disable-version-check --json --json-output=semgrep-community-rules.json .
        env:
          SEMGREP_RULES: auto
      - name: Upload json artifact - Community Rules
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-community-rules
          path: semgrep-community-rules.json
            
      - name: Semgrep with Boost Curated Rules
        run: semgrep scan --oss-only --quiet --disable-version-check --json --json-output=semgrep-boost-rules.json .
        env:
          SEMGREP_RULES: https://assets.build.boostsecurity.io/semgrep-canary/all-sast-rules.yml
      - name: Upload json artifact - Boost Rules
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-boost-rules
          path: semgrep-boost-rules.json
